### ISSUE TITLE
Memcache for all PHP version

### ISSUE THREAD

**Issue by kenny-lee-1992** [marius-nyxpoint/vagrant-php5.2#1]
Dear,

Thanks so much for your vagrant package. Currently, i can run our app both php version. But when i install new memcache extension, so it just run for php 5.3.10 and not run for 5.2.17.

So can you help me configure this  to run memcache on both?

Thanks and Best Regards,

**Comment by marius-cojocariu** [comment]
Hi,

By default, the system runs php 5.3 and you have to activate 5.2 per <VirtualHost> definition. 

To activate php 5.2 add 'Include php52.conf' to <VirtualHost> definition for the sites which should use this version and restart apache.
